name: Publish

on:
  release:
    types: 
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Setup GIT
        run: |
          git config --global user.email "ci@inshur.com"
          git config --global user.name "ci"

      - name: Install Packages
        run: yarn install

      - name: Update Version
        run: npm version ${{ github.event.release.name }}

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
